server:
 servlet:
  context-path: /person
spring:
 datasource:
  url: jdbc:mysql://localhost:3306/pegasus_test_person?createDatabaseIfNotExist=true&autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
  username: root
  password: mysql
  platform: mysql
 jpa:
  database-platform: org.hibernate.dialect.MySQL57Dialect
  hibernate.ddl-auto: update
 main:
  allow-bean-definition-overriding: true
 profiles:
  active: development
app:
 api:
  basic:
   username: testPersonUser
   password: xCMbk5081
springdoc:
 api-docs:
  path: /api-docs
 swagger-ui:
  path: /swagger-ui.html
 version: 3.0
